### ISSUE TITLE
report command: download logs of failed tests only

### ISSUE THREAD

**Issue by bocekm** [danmyway/tesar#42]
**Is your feature request related to a problem? Please describe.**
Right now I can download convert2rhel log files from all tests that have run for a give Testing Farm job. It's a lot of data to download and it takes time. I'm interesting in logs of only the failed tests though.

**Describe the solution you'd like**
Add filtering to the report download feature.

**Comment by pholica** [comment]
Hello @bocekm , please check the #49 if it meets your requirements. Thank you.

**Comment by bocekm** [comment]
I believe it does, thank you, @pholica!
